# Generated by Django 3.1.3 on 2021-11-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favamealapi', '0002_auto_20201116_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='favorite',
            field=models.ManyToManyField(through='favamealapi.FavoriteRestaurant', to='favamealapi.Restaurant'),
        ),
    ]
